name: Release

on:
  release:
    types: [published]

env:
  GO_VERSION: "1.21"

permissions:
  contents: write

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: cd web && npm install &&  npm run build
      - uses: actions/cache/save@v3
        with:
          path: web/dist
          key: web-dist-${{ github.event.release.tag_name }}

  webhook:
    runs-on: ubuntu-latest
    needs: web
    strategy:
      fail-fast: false
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache/restore@v3
        id: cache
        with:
          path: web/dist
          key: web-dist-${{ github.event.release.tag_name }}
          fail-on-cache-miss: true

      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: go get .

      - name: Build
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="-s -w" -o bin/webhook-${{ github.event.release.tag_name }}-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: bin/webhook-*
          tag_name: ${{ github.event.release.tag_name }}
